language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"
before_install:
  - sudo apt-get install gfortran
install:
  - pip install numpy
script:
  - python setup.py install
  - cd example
  - python BSC.py
  - python BEC.py

