version: 1.0.{build}
init:
- cmd: >-
    set path=%path%;C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;C:\Miniconda-x64\Scripts

install:
- cmd: >-
    C:\Miniconda-x64\Scripts\conda.exe install --yes numpy twine

    copy .\msvc9compiler.py C:\Miniconda-x64\Lib\distutils\msvc9compiler.py
build_script:
- cmd: C:\Miniconda-x64\python.exe setup.py install
test_script:
- cmd: >-
    C:\Miniconda-x64\python.exe tests/ace_cream_test.py

    C:\Miniconda-x64\python.exe example/BSC.py

    C:\Miniconda-x64\python.exe example/BEC.py

    C:\Miniconda-x64\python.exe example/continuous.py

    C:\Miniconda-x64\python.exe -m twine upload build/ace_cream* -u zhaofeng-shu33
